# Analysis v2: does the price-per-m² ranking hold with the whole city?

The original analysis (June 2026, 1,901 Argenprop listings, 30 barrios with n ≥ 10) found:

1. a clear price-per-m² map with **Puerto Madero in its own tier**, no overlap with any other barrio;
2. location, not unit size, drives price per m²;
3. expensive overall ≠ expensive per m².

This notebook re-runs only the **main ranking** (finding 1) on the expanded dataset
(September 2026, 59,069 listings from Mercado Libre + Argenprop, 48 barrios) and compares
it with the original, using the same method: median of `price / covered_m2` per barrio,
barrios with at least 10 listings.

In [1]:
import subprocess, io
import pandas as pd

pd.set_option("display.width", 160)
MIN_N = 10   # same floor as the original analysis

v2 = pd.read_csv("../data/listings.csv")
# original dataset, straight from the commit that published it
v1 = pd.read_csv(io.BytesIO(subprocess.check_output(["git", "show", "e601433:data/listings.csv"])))
print(f"v1: {len(v1):,} listings, {v1.neighborhood.nunique()} barrios")
print(f"v2: {len(v2):,} listings, {v2.neighborhood.nunique()} barrios  (sources: {v2.source.value_counts().to_dict()})")

v1: 1,901 listings, 39 barrios
v2: 59,069 listings, 48 barrios  (sources: {'mercadolibre': 58999, 'argenprop': 70})

In [2]:
def ranking(df):
    g = (df.groupby("neighborhood")
           .agg(n=("price_per_m2", "size"),
                median_usd_m2=("price_per_m2", "median"),
                p25=("price_per_m2", lambda s: s.quantile(.25)),
                p75=("price_per_m2", lambda s: s.quantile(.75)))
           .round(0))
    g = g[g.n >= MIN_N].sort_values("median_usd_m2", ascending=False)
    g["rank"] = range(1, len(g) + 1)
    return g

r1, r2 = ranking(v1), ranking(v2)
print(f"barrios ranked: v1 = {len(r1)}, v2 = {len(r2)}")

barrios ranked: v1 = 30, v2 = 48

## 1. Ranking v2: median USD/m² by barrio, all 48

In [3]:
r2[["rank", "n", "median_usd_m2", "p25", "p75"]].astype(int)

                     rank     n  median_usd_m2   p25   p75
neighborhood
Puerto Madero           1   978           6190  5246  7756
Palermo                 2  9568           3912  3121  5000
Núñez                   3  3063           3879  3242  4626
Belgrano                4  5299           3699  3000  4654
Colegiales              5  1257           3375  2822  3967
Saavedra                6  1235           3310  2778  3886
Coghlan                 7   450           3157  2744  3598
Villa Urquiza           8  2460           3112  2644  3636
Villa Devoto            9  1496           3110  2561  3788
Chacarita              10   510           3096  2666  3569
Recoleta               11  4912           3037  2436  3950
Villa Ortúzar          12   458           2932  2518  3557
Villa Crespo           13  2259           2924  2350  3322
Caballito              14  3843           2736  2189  3384
Villa Pueyrredón       15   390           2635  2312  2947
Parque Chas            16   182           2587  2328  2881
Retiro                 17   877           2571  2069  3333
Villa del Parque       18  1091           2534  2215  2959
Agronomía              19   104           2478  2129  2865
Almagro                20  2539           2475  1964  2976
San Telmo              21   955           2464  1842  3056
Monte Castro           22   351           2394  2005  2696
Parque Chacabuco       23   515           2379  1875  2838
Barracas               24   943           2353  1790  2874
Liniers                25   706           2312  1729  2804
Villa Luro             26   907           2292  2063  2735
Villa Real             27   117           2291  1840  2764
Mataderos              28   560           2287  1758  2769
La Paternal            29   272           2282  1946  2594
Boedo                  30   674           2280  1913  2650
Villa Santa Rita       31   178           2210  1922  2659
Flores                 32  1821           2111  1688  2567
Villa General Mitre    33   199           2108  1721  2452
San Cristóbal          34   978           2094  1651  2528
Vélez Sársfield        35   116           1975  1700  2246
Monserrat              36  1100           1964  1583  2628
Villa Riachuelo        37    18           1938  1628  2212
Versalles              38    80           1888  1583  2385
Parque Patricios       39   327           1862  1560  2312
Floresta               40   457           1827  1554  2241
Parque Avellaneda      41   145           1825  1340  2085
San Nicolás            42   872           1816  1536  2200
Balvanera              43  2514           1771  1474  2216
La Boca                44   283           1434  1193  1667
Constitución           45   335           1410  1101  1824
Nueva Pompeya          46    59           1136   836  1530
Villa Lugano           47   563           1053   870  1714
Villa Soldati          48    53            957   613  1567

## 2. Comparison with the original ranking

`rank_v1` is the barrio's position among the 30 barrios of the original analysis, `rank_v2`
among the 48 of this one. Because 18 barrios are new, a raw rank shift is not comparable, so
`rank_v1_in_v2` re-ranks the v2 medians **restricted to the 30 original barrios**; `shift` is
`rank_v1 - rank_v1_in_v2` (positive = moved up).

In [4]:
cmp = r2.join(r1[["rank", "n", "median_usd_m2"]].add_suffix("_v1"), how="left")
cmp = cmp.rename(columns={"rank": "rank_v2", "n": "n_v2", "median_usd_m2": "median_v2"})
old = cmp[cmp.rank_v1.notna()].sort_values("median_v2", ascending=False).copy()
old["rank_v1_in_v2"] = range(1, len(old) + 1)
cmp["rank_v1_in_v2"] = old["rank_v1_in_v2"]
cmp["shift"] = cmp["rank_v1"] - cmp["rank_v1_in_v2"]
cmp["median_change_%"] = ((cmp.median_v2 / cmp.median_usd_m2_v1 - 1) * 100).round(0)
cmp["new"] = cmp.rank_v1.isna()

cols = ["rank_v2", "n_v2", "median_v2", "rank_v1", "n_v1", "median_usd_m2_v1", "rank_v1_in_v2", "shift", "median_change_%"]
out = cmp[cols].copy()
for c in cols:
    out[c] = out[c].astype("Int64")
out.index = [f"{b}  *NEW*" if new else b for b, new in zip(cmp.index, cmp.new)]
out

                            rank_v2  n_v2  median_v2  rank_v1  n_v1  median_usd_m2_v1  rank_v1_in_v2  shift  median_change_%
Puerto Madero                     1   978       6190        1    12              5788              1      0                7
Palermo                           2  9568       3912        3   246              3129              2      1               25
Núñez                             3  3063       3879        5    49              3014              3      2               29
Belgrano                          4  5299       3699        7   187              2889              4      3               28
Colegiales                        5  1257       3375        8    45              2875              5      3               17
Saavedra                          6  1235       3310        4    30              3070              6     -2                8
Coghlan  *NEW*                    7   450       3157     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Villa Urquiza                     8  2460       3112        6   122              2921              7     -1                7
Villa Devoto                      9  1496       3110        2    79              3157              8     -6               -1
Chacarita                        10   510       3096       10    11              2706              9      1               14
Recoleta                         11  4912       3037       13   179              2560             10      3               19
Villa Ortúzar  *NEW*             12   458       2932     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Villa Crespo                     13  2259       2924       19    64              2314             11      8               26
Caballito                        14  3843       2736       15   196              2362             12      3               16
Villa Pueyrredón                 15   390       2635        9    17              2725             13     -4               -3
Parque Chas  *NEW*               16   182       2587     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Retiro                           17   877       2571       14    17              2438             14      0                5
Villa del Parque                 18  1091       2534       11    54              2662             15     -4               -5
Agronomía  *NEW*                 19   104       2478     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Almagro                          20  2539       2475       18   100              2334             16      2                6
San Telmo                        21   955       2464       28    11              1667             17     11               48
Monte Castro                     22   351       2394       16    21              2348             18     -2                2
Parque Chacabuco                 23   515       2379       21    24              2213             19      2                8
Barracas                         24   943       2353       25    20              1907             20      5               23
Liniers                          25   706       2312       20    20              2286             21     -1                1
Villa Luro                       26   907       2292       17    20              2342             22     -5               -2
Villa Real  *NEW*                27   117       2291     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Mataderos                        28   560       2287       12    15              2630             23    -11              -13
La Paternal  *NEW*               29   272       2282     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Boedo                            30   674       2280       22    20              2078             24     -2               10
Villa Santa Rita  *NEW*          31   178       2210     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Flores                           32  1821       2111       23    61              2000             25     -2                6
Villa General Mitre  *NEW*       33   199       2108     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
San Cristóbal                    34   978       2094       24    24              1916             26     -2                9
Vélez Sársfield  *NEW*           35   116       1975     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Monserrat                        36  1100       1964       26    23              1771             27     -1               11
Villa Riachuelo  *NEW*           37    18       1938     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Versalles  *NEW*                 38    80       1888     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Parque Patricios  *NEW*          39   327       1862     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Floresta                         40   457       1827       30    13              1620             28      2               13
Parque Avellaneda  *NEW*         41   145       1825     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
San Nicolás                      42   872       1816       27    39              1706             29     -2                6
Balvanera                        43  2514       1771       29   137              1639             30     -1                8
La Boca  *NEW*                   44   283       1434     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Constitución  *NEW*              45   335       1410     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Nueva Pompeya  *NEW*             46    59       1136     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Villa Lugano  *NEW*              47   563       1053     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>
Villa Soldati  *NEW*             48    53        957     <NA>  <NA>              <NA>           <NA>   <NA>             <NA>

### Notable movers (|shift| ≥ 5 positions among the original 30) and new barrios

In [5]:
movers = cmp[cmp["shift"].abs() >= 5].sort_values("shift", ascending=False)
print("MOVED UP:")
for b, r in movers[movers["shift"] > 0].iterrows():
    print(f"  {b:20} v1 #{int(r.rank_v1):2} -> #{int(r.rank_v1_in_v2):2} among the same 30  (median {int(r.median_usd_m2_v1):,} -> {int(r.median_v2):,} USD/m², n {int(r.n_v1)} -> {int(r.n_v2):,})")
print("MOVED DOWN:")
for b, r in movers[movers["shift"] < 0].iterrows():
    print(f"  {b:20} v1 #{int(r.rank_v1):2} -> #{int(r.rank_v1_in_v2):2} among the same 30  (median {int(r.median_usd_m2_v1):,} -> {int(r.median_v2):,} USD/m², n {int(r.n_v1)} -> {int(r.n_v2):,})")
print("\nNEW BARRIOS (no or too few listings in v1), with their v2 rank out of 48:")
for b, r in cmp[cmp.new].iterrows():
    print(f"  #{int(r.rank_v2):2} {b:20} median {int(r.median_v2):,} USD/m²  n={int(r.n_v2):,}")
# barrios that were ranked in v1 but do not reach n>=10 in v2 (should be none)
print("\nDropped from the ranking:", sorted(set(r1.index) - set(r2.index)) or "none")

MOVED UP:
  San Telmo            v1 #28 -> #17 among the same 30  (median 1,667 -> 2,464 USD/m², n 11 -> 955)
  Villa Crespo         v1 #19 -> #11 among the same 30  (median 2,314 -> 2,924 USD/m², n 64 -> 2,259)
  Barracas             v1 #25 -> #20 among the same 30  (median 1,907 -> 2,353 USD/m², n 20 -> 943)
MOVED DOWN:
  Villa Luro           v1 #17 -> #22 among the same 30  (median 2,342 -> 2,292 USD/m², n 20 -> 907)
  Villa Devoto         v1 # 2 -> # 8 among the same 30  (median 3,157 -> 3,110 USD/m², n 79 -> 1,496)
  Mataderos            v1 #12 -> #23 among the same 30  (median 2,630 -> 2,287 USD/m², n 15 -> 560)

NEW BARRIOS (no or too few listings in v1), with their v2 rank out of 48:
  # 7 Coghlan              median 3,157 USD/m²  n=450
  #12 Villa Ortúzar        median 2,932 USD/m²  n=458
  #16 Parque Chas          median 2,587 USD/m²  n=182
  #19 Agronomía            median 2,478 USD/m²  n=104
  #27 Villa Real           median 2,291 USD/m²  n=117
  #29 La Paternal          median 2,282 USD/m²  n=272
  #31 Villa Santa Rita     median 2,210 USD/m²  n=178
  #33 Villa General Mitre  median 2,108 USD/m²  n=199
  #35 Vélez Sársfield      median 1,975 USD/m²  n=116
  #37 Villa Riachuelo      median 1,938 USD/m²  n=18
  #38 Versalles            median 1,888 USD/m²  n=80
  #39 Parque Patricios     median 1,862 USD/m²  n=327
  #41 Parque Avellaneda    median 1,825 USD/m²  n=145
  #44 La Boca              median 1,434 USD/m²  n=283
  #45 Constitución         median 1,410 USD/m²  n=335
  #46 Nueva Pompeya        median 1,136 USD/m²  n=59
  #47 Villa Lugano         median 1,053 USD/m²  n=563
  #48 Villa Soldati        median 957 USD/m²  n=53

Dropped from the ranking: none

## 3. Is Puerto Madero still in its own tier?

"Own tier" in the original report meant two things: nearly double the next barrio at the
median, and **no overlap** of its distribution with any other barrio's. Both are checked here,
the second by comparing Puerto Madero's 10th percentile with every other barrio's 90th.

In [6]:
for name, df, r in [("v1", v1, r1), ("v2", v2, r2)]:
    pm = df[df.neighborhood == "Puerto Madero"].price_per_m2
    second = r.index[1]
    gap = r.median_usd_m2.iloc[0] / r.median_usd_m2.iloc[1]
    others = df[df.neighborhood != "Puerto Madero"]
    p90 = others.groupby("neighborhood").price_per_m2.quantile(.9)
    p90 = p90[p90.index.isin(r.index)]
    overlap = (p90 > pm.quantile(.1)).sum()
    print(f"{name}: Puerto Madero median {int(pm.median()):,} (n={len(pm):,}) vs #2 {second} {int(r.median_usd_m2.iloc[1]):,}  -> {gap:.2f}x")
    print(f"     PM p10 = {int(pm.quantile(.1)):,}, PM p25 = {int(pm.quantile(.25)):,}; barrios whose p90 exceeds PM's p10: {overlap}"
          + ("" if overlap == 0 else f"  -> {', '.join(f'{b} ({int(v):,})' for b, v in p90[p90 > pm.quantile(.1)].sort_values(ascending=False).items())}"))
    print(f"     share of PM listings below the #2 barrio's median: {(pm < r.median_usd_m2.iloc[1]).mean():.0%}\n")

v1: Puerto Madero median 5,788 (n=12) vs #2 Villa Devoto 3,157  -> 1.83x
     PM p10 = 4,643, PM p25 = 5,146; barrios whose p90 exceeds PM's p10: 0
     share of PM listings below the #2 barrio's median: 0%

v2: Puerto Madero median 6,190 (n=978) vs #2 Palermo 3,912  -> 1.58x
     PM p10 = 4,590, PM p25 = 5,246; barrios whose p90 exceeds PM's p10: 6  -> Palermo (6,140), Núñez (6,025), Belgrano (6,000), Recoleta (5,000), Villa Devoto (4,681), Colegiales (4,642)
     share of PM listings below the #2 barrio's median: 3%

## 4. Finding 2 — location vs unit size

Original method: a scatter of each barrio's median unit size against its median USD/m² (n ≥ 10),
read visually as "no pattern", with Puerto Madero (largest units, highest USD/m²) as the counter-example
to a small-unit premium. Here the same barrio-level view gets a number (Spearman/Pearson, with and
without Puerto Madero), and — new, only possible with 59k listings — a listing-level check: how much
of the variation in USD/m² is explained by the barrio, how much by unit size, and what size does
*within* a barrio.

In [7]:
import numpy as np

def spearman(a, b):
    # Pearson correlation of ranks == Spearman, without needing scipy
    return a.rank().corr(b.rank())

def barrio_table(df):
    g = (df.groupby("neighborhood")
           .agg(n=("price", "size"), median_usd_m2=("price_per_m2", "median"),
                median_price=("price", "median"), median_m2=("covered_m2", "median"))
           .round(0))
    return g[g.n >= MIN_N]

b1, b2 = barrio_table(v1), barrio_table(v2)

print("Barrio level: correlation of median unit size vs median USD/m²")
for name, b in [("v1 (30 barrios)", b1), ("v2 (48 barrios)", b2)]:
    for label, bb in [("all", b), ("without Puerto Madero", b.drop("Puerto Madero"))]:
        sp = spearman(bb.median_m2, bb.median_usd_m2)
        pe = bb.median_m2.corr(bb.median_usd_m2)
        print(f"  {name:16} {label:24} Spearman {sp:+.2f}   Pearson {pe:+.2f}")
print("\nMedian unit size by barrio, v2 (top/bottom 5 by USD/m²):")
print(b2.sort_values("median_usd_m2", ascending=False)[["median_usd_m2", "median_m2"]].astype(int).iloc[list(range(5)) + list(range(-5, 0))].to_string())

Barrio level: correlation of median unit size vs median USD/m²
  v1 (30 barrios)  all                      Spearman +0.22   Pearson +0.69
  v1 (30 barrios)  without Puerto Madero    Spearman +0.13   Pearson +0.15
  v2 (48 barrios)  all                      Spearman +0.12   Pearson +0.45
  v2 (48 barrios)  without Puerto Madero    Spearman +0.06   Pearson -0.00

Median unit size by barrio, v2 (top/bottom 5 by USD/m²):
               median_usd_m2  median_m2
neighborhood
Puerto Madero           6190         92
Palermo                 3912         50
Núñez                   3879         51
Belgrano                3699         57
Colegiales              3375         57
La Boca                 1434         50
Constitución            1410         46
Nueva Pompeya           1136         59
Villa Lugano            1053         55
Villa Soldati            957         65

In [8]:
# Listing level (v2 only; v1 was too thin). Work in logs so the ratios are additive.
d = v2.copy()
d["ly"] = np.log(d.price_per_m2)
d["lm"] = np.log(d.covered_m2)

def r2_categorical(y, groups):
    # share of variance explained by group means
    within = y.groupby(groups).transform("mean")
    return 1 - ((y - within) ** 2).sum() / ((y - y.mean()) ** 2).sum()

r2_barrio = r2_categorical(d.ly, d.neighborhood)
r_size = d.lm.corr(d.ly)
r2_size = r_size ** 2
# size within barrio: demean both variables by barrio, then correlate
d["ly_w"] = d.ly - d.groupby("neighborhood").ly.transform("mean")
d["lm_w"] = d.lm - d.groupby("neighborhood").lm.transform("mean")
r_size_within = d.lm_w.corr(d.ly_w)
# both together: barrio dummies + log size (residual of within-barrio regression)
slope = np.polyfit(d.lm_w, d.ly_w, 1)[0]
resid = d.ly_w - slope * d.lm_w
r2_both = 1 - (resid ** 2).sum() / ((d.ly - d.ly.mean()) ** 2).sum()

print(f"Listing level, n = {len(d):,}  (log USD/m²)")
print(f"  R² barrio only            : {r2_barrio:.3f}")
print(f"  R² unit size only         : {r2_size:.3f}   (Pearson r = {r_size:+.3f}, Spearman = {spearman(d.covered_m2, d.price_per_m2):+.3f})")
print(f"  R² barrio + size          : {r2_both:.3f}   -> size adds {r2_both - r2_barrio:.3f} on top of barrio")
print(f"  size within barrio        : r = {r_size_within:+.3f}; elasticity {slope:+.3f}  (doubling m² changes USD/m² by {(2**slope - 1) * 100:+.0f}%)")
print()
print("Per-barrio Spearman(covered_m2, USD/m²), v2:")
wb = d.groupby("neighborhood").apply(lambda g: spearman(g.covered_m2, g.price_per_m2)).round(2)
print(f"  median across barrios {wb.median():+.2f}, range {wb.min():+.2f} .. {wb.max():+.2f}; positive in {(wb > 0).sum()} of {len(wb)} barrios")
print("  most negative:", wb.sort_values().head(5).to_dict())
print("  most positive:", wb.sort_values().tail(5).to_dict())
print()
print("USD/m² by size bucket, v2 (median), overall and inside Palermo:")
bins = [15, 35, 50, 70, 100, 150, 500]
d["size_bucket"] = pd.cut(d.covered_m2, bins)
tab = d.groupby("size_bucket", observed=True).price_per_m2.agg(n="size", median="median")
tab["Palermo"] = d[d.neighborhood == "Palermo"].groupby("size_bucket", observed=True).price_per_m2.median()
tab["Villa Lugano"] = d[d.neighborhood == "Villa Lugano"].groupby("size_bucket", observed=True).price_per_m2.median()
print(tab.round(0).astype("Int64").to_string())

Listing level, n = 59,069  (log USD/m²)
  R² barrio only            : 0.463
  R² unit size only         : 0.007   (Pearson r = +0.082, Spearman = +0.034)
  R² barrio + size          : 0.463   -> size adds 0.000 on top of barrio
  size within barrio        : r = -0.005; elasticity -0.003  (doubling m² changes USD/m² by -0%)

Per-barrio Spearman(covered_m2, USD/m²), v2:
  median across barrios -0.04, range -0.62 .. +0.35; positive in 18 of 48 barrios
  most negative: {'Nueva Pompeya': -0.62, 'San Nicolás': -0.52, 'Constitución': -0.5, 'San Telmo': -0.49, 'Monserrat': -0.47}
  most positive: {'Villa Riachuelo': 0.23, 'Villa Ortúzar': 0.26, 'Núñez': 0.27, 'Puerto Madero': 0.28, 'Villa Devoto': 0.35}

USD/m² by size bucket, v2 (median), overall and inside Palermo:
                 n  median  Palermo  Villa Lugano
size_bucket
(15, 35]     11563    2917     3870          1903
(35, 50]     17022    2919     3854          1111
(50, 70]     12539    2750     3750          1000
(70, 100]     9289    2792     3763           918
(100, 150]    5196    3214     4214           696
(150, 500]    3454    3572     5110          1129

## 5. Finding 3 — total price vs price per m² rank the city differently

Original method: rank barrios (n ≥ 10) by median total price and by median USD/m²; a barrio far
apart on the two lists pays for size, not for a per-m² premium. Recoleta was the case (3rd by total
price, 13th by USD/m²). Same computation on v1 and v2; `divergence = rank_price - rank_usd_m2`
(positive = ranks higher by total price than by USD/m², i.e. large units; negative = the opposite).

In [9]:
def divergence(b):
    b = b.copy()
    b["rank_usd_m2"] = b.median_usd_m2.rank(ascending=False, method="min").astype(int)
    b["rank_price"] = b.median_price.rank(ascending=False, method="min").astype(int)
    b["divergence"] = b.rank_price - b.rank_usd_m2
    return b

d1, d2 = divergence(b1), divergence(b2)
print("Rank correlation between the two orderings (Spearman):")
print(f"  v1: {spearman(d1.rank_price, d1.rank_usd_m2):.2f}   v2: {spearman(d2.rank_price, d2.rank_usd_m2):.2f}")
print()
for name, dd, big in [("v1", d1, 4), ("v2", d2, 6)]:
    rec = dd.loc["Recoleta"]; bel = dd.loc["Belgrano"]
    print(f"{name}: Recoleta  #{int(rec.rank_price)} by total price, #{int(rec.rank_usd_m2)} by USD/m²  (median price {int(rec.median_price):,}, {int(rec.median_m2)} m², {int(rec.median_usd_m2):,} USD/m²)")
    print(f"{name}: Belgrano  #{int(bel.rank_price)} by total price, #{int(bel.rank_usd_m2)} by USD/m²  (median price {int(bel.median_price):,}, {int(bel.median_m2)} m²)")
    print(f"{name}: barrios with |divergence| >= {big}:")
    for b, r in dd[dd.divergence.abs() >= big].sort_values("divergence", ascending=False).iterrows():
        print(f"     {b:20} price #{int(r.rank_price):2} vs USD/m² #{int(r.rank_usd_m2):2}  ({int(r.divergence):+d})   {int(r.median_price):>9,} USD  {int(r.median_m2):3} m²  {int(r.median_usd_m2):,} USD/m²")
    print()

Rank correlation between the two orderings (Spearman):
  v1: 0.78   v2: 0.93

v1: Recoleta  #4 by total price, #13 by USD/m²  (median price 179,000, 70 m², 2,560 USD/m²)
v1: Belgrano  #3 by total price, #7 by USD/m²  (median price 185,000, 62 m²)
v1: barrios with |divergence| >= 4:
     Chacarita            price #26 vs USD/m² #10  (+16)      90,000 USD   33 m²  2,706 USD/m²
     Saavedra             price #14 vs USD/m² # 4  (+10)     127,801 USD   42 m²  3,070 USD/m²
     Retiro               price #23 vs USD/m² #14  (+9)     110,000 USD   53 m²  2,438 USD/m²
     Villa Urquiza        price #13 vs USD/m² # 6  (+7)     135,000 USD   49 m²  2,921 USD/m²
     Villa del Parque     price #16 vs USD/m² #11  (+5)     120,500 USD   50 m²  2,662 USD/m²
     San Cristóbal        price #28 vs USD/m² #24  (+4)      84,500 USD   50 m²  1,916 USD/m²
     Belgrano             price # 3 vs USD/m² # 7  (-4)     185,000 USD   62 m²  2,889 USD/m²
     Mataderos            price # 8 vs USD/m² #12  (-4)     158,000 USD   68 m²  2,630 USD/m²
     Caballito            price # 9 vs USD/m² #15  (-6)     153,450 USD   62 m²  2,362 USD/m²
     Floresta             price #23 vs USD/m² #30  (-7)     110,000 USD   67 m²  1,620 USD/m²
     Villa Crespo         price #12 vs USD/m² #19  (-7)     135,500 USD   54 m²  2,314 USD/m²
     Recoleta             price # 4 vs USD/m² #13  (-9)     179,000 USD   70 m²  2,560 USD/m²
     Parque Chacabuco     price #10 vs USD/m² #21  (-11)     149,000 USD   62 m²  2,213 USD/m²

v2: Recoleta  #3 by total price, #11 by USD/m²  (median price 198,000, 62 m², 3,037 USD/m²)
v2: Belgrano  #2 by total price, #4 by USD/m²  (median price 215,000, 57 m²)
v2: barrios with |divergence| >= 6:
     Agronomía            price #33 vs USD/m² #19  (+14)     103,300 USD   44 m²  2,478 USD/m²
     San Telmo            price #34 vs USD/m² #21  (+13)     102,300 USD   42 m²  2,464 USD/m²
     Parque Chas          price #23 vs USD/m² #16  (+7)     115,000 USD   42 m²  2,587 USD/m²
     Vélez Sársfield      price #42 vs USD/m² #35  (+7)      87,500 USD   42 m²  1,975 USD/m²
     Balvanera            price #37 vs USD/m² #43  (-6)      92,000 USD   52 m²  1,771 USD/m²
     Mataderos            price #21 vs USD/m² #28  (-7)     119,000 USD   52 m²  2,287 USD/m²
     Recoleta             price # 3 vs USD/m² #11  (-8)     198,000 USD   62 m²  3,037 USD/m²
     Villa Riachuelo      price #29 vs USD/m² #37  (-8)     106,250 USD   54 m²  1,938 USD/m²
     Retiro               price # 8 vs USD/m² #17  (-9)     175,000 USD   60 m²  2,571 USD/m²
     Flores               price #22 vs USD/m² #32  (-10)     118,000 USD   58 m²  2,111 USD/m²
     Versalles            price #27 vs USD/m² #38  (-11)     109,000 USD   56 m²  1,888 USD/m²

In [10]:
cols = ["n", "median_price", "median_m2", "median_usd_m2", "rank_price", "rank_usd_m2", "divergence"]
d2.sort_values("rank_price")[cols].astype(int)

                        n  median_price  median_m2  median_usd_m2  rank_price  rank_usd_m2  divergence
neighborhood
Puerto Madero         978        530000         92           6190           1            1           0
Belgrano             5299        215000         57           3699           2            4          -2
Recoleta             4912        198000         62           3037           3           11          -8
Palermo              9568        195000         50           3912           4            2           2
Núñez                3063        192000         51           3879           5            3           2
Villa Devoto         1496        184000         64           3110           6            9          -3
Colegiales           1257        183000         57           3375           7            5           2
Retiro                877        175000         60           2571           8           17          -9
Saavedra             1235        160650         48           3310           9            6           3
Villa Urquiza        2460        155000         49           3112          10            8           2
Caballito            3843        150000         55           2736          11           14          -3
Coghlan               450        148256         47           3157          12            7           5
Villa Ortúzar         458        141700         50           2932          13           12           1
Villa Crespo         2259        137500         49           2924          14           13           1
Chacarita             510        136900         47           3096          15           10           5
Villa del Parque     1091        128000         50           2534          16           18          -2
Villa Pueyrredón      390        125000         50           2635          17           15           2
Almagro              2539        124900         50           2475          18           20          -2
Parque Chacabuco      515        122000         55           2379          19           23          -4
Barracas              943        120000         55           2353          20           24          -4
Mataderos             560        119000         52           2287          21           28          -7
Flores               1821        118000         58           2111          22           32         -10
Parque Chas           182        115000         42           2587          23           16           7
Liniers               706        115000         54           2312          23           25          -2
Monte Castro          351        114900         48           2394          25           22           3
Villa Real            117        110000         51           2291          26           27          -1
Versalles              80        109000         56           1888          27           38         -11
Villa Luro            907        107000         46           2292          28           26           2
Villa Riachuelo        18        106250         54           1938          29           37          -8
Boedo                 674        105000         45           2280          30           30           0
Villa General Mitre   199        105000         47           2108          30           33          -3
La Paternal           272        104000         45           2282          32           29           3
Agronomía             104        103300         44           2478          33           19          14
San Telmo             955        102300         42           2464          34           21          13
Villa Santa Rita      178         99000         46           2210          35           31           4
Monserrat            1100         93000         43           1964          36           36           0
Balvanera            2514         92000         52           1771          37           43          -6
San Nicolás           872         89000         48           1816          38           42          -4
San Cristóbal         978         89000         42           2094          38           34           4
Parque Patricios      327         89000         48           1862          38           39          -1
Floresta              457         89000         47           1827          38           40          -2
Vélez Sársfield       116         87500         42           1975          42           35           7
Parque Avellaneda     145         85000         51           1825          43           41           2
La Boca               283         70000         50           1434          44           44           0
Constitución          335         67500         46           1410          45           45           0
Villa Soldati          53         65000         65            957          46           48          -2
Nueva Pompeya          59         60000         59           1136          47           46           1
Villa Lugano          563         59900         55           1053          48           47           1

## Read-out

**Finding 2 (location, not size) — holds, and is now much stronger than the original could show.**

- Barrio level, same method as June: Spearman(median m², median USD/m²) = +0.12 across 48 barrios,
  +0.06 without Puerto Madero (v1: +0.22 / +0.13). Pearson +0.45 is entirely Puerto Madero (−0.00 without it).
  No relation, as before.
- Listing level (new, n = 59,069, log USD/m²): barrio explains **46%** of the variance; unit size explains
  **0.7%**, and **0.0% on top of barrio**. Within a barrio the size elasticity is −0.003: doubling the m²
  changes USD/m² by 0%. The small-unit premium hypothesis is rejected on average, more decisively than in June.
- Nuance the big sample adds: the *average* zero hides two opposite local patterns. In central and
  southern barrios small units do carry a premium (within-barrio Spearman: Nueva Pompeya −0.62, San Nicolás
  −0.52, Constitución −0.50, San Telmo −0.49, Monserrat −0.47), while in the north large units do
  (Villa Devoto +0.35, Puerto Madero +0.28, Núñez +0.27). And the overall size curve is U-shaped:
  15–100 m² sits flat at ~2,750–2,900 USD/m², above 100 m² it rises to 3,200–3,600 (Palermo: 3,750–3,870
  up to 5,110 for 150+ m²). "Size does not matter" is true on average; "a bigger unit never pays more
  per m²" is not.

**Finding 3 (total price and USD/m² rank the city differently) — holds, but the divergence is smaller than it looked.**

- Spearman between the two rankings: **0.78 in v1 → 0.93 in v2**. With 10–20 listings per barrio, part of
  the June divergence was sampling noise; with the whole city the two orderings mostly agree.
- Recoleta is still the clearest case: **#3 by median total price (198,000 USD) vs #11 by USD/m² (3,037)**,
  because its typical unit is 62 m² against Palermo's 50 (v1: #4 vs #13; the report said 3rd because its
  chart left Puerto Madero out). Belgrano's "gentler version" has essentially disappeared: #2 vs #4.
- Same pattern (large units, expensive in total, mid-table per m²): Retiro #8 vs #17 (60 m²), Flores #22 vs
  #32 (58 m²), Versalles #27 vs #38, Mataderos #21 vs #28. The mirror image (small units, cheap in total,
  pricey per m²): San Telmo #34 vs #21 (42 m²), Agronomía #33 vs #19 (44 m²), Parque Chas #23 vs #16 (42 m²).

**Honesty rule, as in section 2:** everything above compares orderings and within-dataset structure, which is
robust. Absolute levels (e.g. Recoleta 179,000 → 198,000 USD) mix a change of source (Mercado Libre vs
Argenprop) with three months, and this notebook cannot separate the two.